### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by larrykluger** [E96/swagger2slate#1]
Congratulations on your project so far! Are you still working on it?

Do you consider the project alpha, beta or released at this point? 

Thanks,
Larry

**Comment by m8rge** [comment]
This project is freezed now. At this point I don't have future plans for this project. You can fork it freely and modify.

**Comment by MikeRalphson** [comment]
@jamesogden @hangtwenty Another (maintained) project to convert Swagger (OpenApi) to Slate is https://github.com/mermade/widdershins

**Comment by floer32** [comment]
Thanks @MikeRalphson for that widdershins link.
