### ISSUE TITLE
PHP parse error

### ISSUE THREAD

**Issue by lavkumarv** [E96/swagger2slate#10]
while executing the command
<code> ./swagger2slate.phar convert swagger.json -o my/index.md</code>

getting this error:

PHP Parse error:  syntax error,
 unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in phar:swagger2slate.phar/index.php on line 13

**Comment by m8rge** [comment]
Please provide swagger.json

**Comment by m8rge** [comment]
php minimum version is 5.5
