### ISSUE TITLE
Any one encounter this error when running this? 

### ISSUE THREAD

**Issue by xinghengwang** [E96/swagger2slate#7]
Warning: explode() expects parameter 2 to be string, array given in phar:///swagger2slate.phar/swagger/Schema.php on line 59

Warning: Invalid argument supplied for foreach() in phar://swagger2slate.phar/swagger/Schema.php on line 62

Warning: end() expects parameter 1 to be array, null given in phar:///swagger2slate.phar/swagger/Schema.php on line 68

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in phar:

**Comment by MikeRalphson** [comment]
As per #1, this project is no longer maintained. Please feel free to try https://github.com/mermade/widdershins with your Swagger definition and report any errors there.

**Comment by m8rge** [comment]
Please provide your swagger.json file
