### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by saikrishnaradarapu** [E96/swagger2slate#9]
$ php swagger2slate.phar convert swagger.json -o index.md

givving:
Segmentation fault

**Comment by MikeRalphson** [comment]
@saikrishnaradarapu Another (maintained) project to convert Swagger (OpenApi) to Slate is https://github.com/mermade/widdershins

**Comment by saikrishnaradarapu** [comment]
Thank you very much @MikeRalphson for helping me..

**Comment by m8rge** [comment]
Please provide your swagger.json file
